AUTH0_CLIENT_ID = 'eH9ApoEVliYbgzNZUV7fg5sNswpd7qqs'
AUTH0_CLIENT_SECRET = 'rZOJ0xqCSp_ZkEcgUG3ZslpHPQXOvf7GcmUW2hKG8HUc0vWXWEWdwkk8nL5HQ_wq'
AUTH0_CALLBACK_URL = 'http://localhost:8080/callback'
AUTH0_DOMAIN = 'udacity-shop.auth0.com'
AUTH0_AUDIENCE = 'agency'
